"""add redeem_codes table

Revision ID: 0335db638ecc
Revises: 6e6542d
Create Date: 2025-11-05 16:19:58.590000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0335db638ecc'
down_revision: Union[str, None] = 'add_stamp_icon'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('redeem_codes',
    sa.Column('id', postgresql.UUID(as_uuid=True), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('membership_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('program_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('customer_user_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('merchant_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('amount', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('is_used', sa.String(), nullable=True),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['customer_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['membership_id'], ['customer_program_memberships.id'], ),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ),
    sa.ForeignKeyConstraint(['program_id'], ['loyalty_programs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index(op.f('ix_redeem_codes_code'), 'redeem_codes', ['code'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_redeem_codes_code'), table_name='redeem_codes')
    op.drop_table('redeem_codes')
    # ### end Alembic commands ###