"""add merchant settings table

Revision ID: 20251109_add_merchant_settings_table
Revises: 20251108_add_merchant_analytics
Create Date: 2025-11-09 00:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20251109_add_merchant_settings_table'
down_revision: Union[str, None] = '20251108_add_merchant_analytics'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('merchant_settings',
    sa.Column('merchant_id', sa.UUID(), nullable=False),
    sa.Column('avg_spend_per_visit_kes', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('baseline_visits_per_customer_per_period', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('avg_reward_cost_kes', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('default_period', sa.String(), nullable=False),
    sa.Column('monthly_subscription_kes', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ),
    sa.PrimaryKeyConstraint('merchant_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('merchant_settings')
    # ### end Alembic commands ###