"""add stamp_icon to loyalty_programs

Revision ID: 20251106_add_stamp_icon_to_loyalty_programs
Revises: 20251105_add_name_to_locations
Create Date: 2025-11-06 00:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'add_stamp_icon'
down_revision: Union[str, None] = '20251105_add_name_to_locations'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('loyalty_programs', sa.Column('stamp_icon', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('loyalty_programs', 'stamp_icon')
    # ### end Alembic commands ###