"""add merchant analytics fields

Revision ID: a7
Revises: a0
Create Date: 2025-11-08 00:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a7'
down_revision: Union[str, None] = 'a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('merchants', sa.Column('average_spend_per_visit', sa.Float(), nullable=True))
    op.add_column('merchants', sa.Column('baseline_visits_per_period', sa.Integer(), nullable=True))
    op.add_column('merchants', sa.Column('reward_cost_estimate', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('merchants', 'reward_cost_estimate')
    op.drop_column('merchants', 'baseline_visits_per_period')
    op.drop_column('merchants', 'average_spend_per_visit')
    # ### end Alembic commands ###